# Generated by Django 4.1.3 on 2023-03-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seo_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'Seo', 'verbose_name_plural': 'Seo'},
        ),
    ]
