# Generated by Django 4.1.3 on 2023-03-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_seo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='shortdescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='shortdescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.TextField(),
        ),
    ]
